import Head from 'next/head';
import Banner from '../components/banner';
import Card from '../components/card';
import s from '../styles/Home.module.css';
import Image from 'next/image';

import coffeeStores from '../data/coffee-stores.json';

export default function Home() {
  const handleOnBannerClick = () => {
    console.log('Hello');
  };
  return (
    <div className={s.container}>
      <Head>
        <title>QahwaXona</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={s.main}>
        <Banner buttonText={'View stores nearby'} handleOnClick={handleOnBannerClick} />
        <div className={s.heroImage}>
          <Image src="/static/hero-image.png" width={700} height={400} />
        </div>
        <div className={s.cardLayout}>
          {coffeeStores.map((cs) => {
            return <Card name={cs.name} imgUrl={cs.imgUrl} href={`/coffee-store/${cs.id}`} />;
          })}
        </div>
      </main>
    </div>
  );
}
