import Head from 'next/head';
import Banner from '../components/banner';
import Card from '../components/card';
import s from '../styles/Home.module.css';
import Image from 'next/image';

import coffeeStoresData from '../data/coffee-stores.json';

export async function getStaticProps(context) {
  return {
    props: {
      coffeeStores: coffeeStoresData,
    },
  };
}

export default function Home({ coffeeStores }) {
  const handleOnBannerClick = () => {
    console.log('Hello');
  };
  return (
    <div className={s.container}>
      <Head>
        <title>QahwaXona</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={s.main}>
        <Banner buttonText={'View stores nearby'} handleOnClick={handleOnBannerClick} />
        <div className={s.heroImage}>
          <Image src="/static/hero-image.png" width={700} height={400} />
        </div>

        {coffeeStores.length && (
          <>
            <h2 className={s.heading2}>Toronto stores</h2>
            <div className={s.cardLayout}>
              {coffeeStores.map((cs) => {
                return (
                  <Card
                    key={cs.id}
                    name={cs.name}
                    imgUrl={cs.imgUrl}
                    href={`/coffee-store/${cs.id}`}
                  />
                );
              })}
            </div>
          </>
        )}
      </main>
    </div>
  );
}
